version: '2.4'

services:
  backend:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: golf-backend
    ports:
      - "5050:5000"
    environment:
      - PORT=5000
      - DB_HOST=database
      - DB_USER=postgres
      - DB_NAME=golf_handicap
      - DB_PASSWORD=your_secure_password
      - DB_PORT=5432
    depends_on:
      - database
    networks:
      - app-network

  frontend:
    build:
      context: ./web-server
      dockerfile: Dockerfile
    container_name: golf-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  database:
    image: postgres:13-alpine
    container_name: golf-database
    environment:
      - POSTGRES_DB=golf_handicap
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_secure_password
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge